<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Warehouses</name>
   <tag></tag>
   <elementGuidId>160cbc94-e9b3-43c5-9faa-e9e53272f1ea</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.fw-bold.text-truncate</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Warehouses')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Warehouses&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>2ca26e16-91ff-4e08-b96e-dcfb1e13f4ca</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-truncate</value>
      <webElementGuid>4c8fc547-f76e-40ba-b9b6-d66be09f54f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/odoo/action-242</value>
      <webElementGuid>99718307-da19-4ba8-99b0-0004e8209937</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Back to &quot;Warehouses&quot;</value>
      <webElementGuid>6af749af-5264-4e81-968a-c2aaad5895a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Warehouses</value>
      <webElementGuid>bef855a4-caaa-4e00-99d9-f5248ff655fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_xxl_form_view h-100 o_form_view o_view_controller o_action&quot;]/div[@class=&quot;o_form_view_container&quot;]/div[@class=&quot;o_control_panel d-flex flex-column gap-3 gap-lg-1 px-3 pt-2 pb-3&quot;]/div[@class=&quot;o_control_panel_main d-flex flex-wrap flex-lg-nowrap justify-content-between align-items-lg-start gap-3 flex-grow-1&quot;]/div[@class=&quot;o_control_panel_breadcrumbs d-flex align-items-center gap-1 order-0 h-lg-100&quot;]/div[@class=&quot;o_breadcrumb d-flex flex-row flex-md-column align-self-stretch justify-content-between min-w-0&quot;]/ol[@class=&quot;breadcrumb flex-nowrap text-nowrap small lh-sm&quot;]/li[@class=&quot;breadcrumb-item d-inline-flex min-w-0 o_back_button&quot;]/a[@class=&quot;fw-bold text-truncate&quot;]</value>
      <webElementGuid>719d0e5c-23c3-411c-a4f6-a3e2d11e4b40</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Warehouses')]</value>
      <webElementGuid>a4c4679b-554f-4b68-9d6f-22b47eb26077</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::a[1]</value>
      <webElementGuid>e589b20d-7a51-4717-a89c-f9fb56ab6d3e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[1]/following::a[1]</value>
      <webElementGuid>507e42ac-58f4-4e7d-875a-822e6c7cdc1f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wqwer'])[2]/preceding::a[1]</value>
      <webElementGuid>a1f81167-97ca-4c7e-bfef-f35b5155a172</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Routes'])[1]/preceding::a[1]</value>
      <webElementGuid>6a90e7b8-8867-4020-b38c-f2c7275f636c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Warehouses']/parent::*</value>
      <webElementGuid>71a17f6e-b3ae-461f-b337-0622d0042a42</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/odoo/action-242')]</value>
      <webElementGuid>83088539-bde6-4459-a4a4-893bc3e47b6c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>ff436e8f-b005-479a-9221-2da5ac0070e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/odoo/action-242' and (text() = 'Warehouses' or . = 'Warehouses')]</value>
      <webElementGuid>fdaf1ee1-ffbd-489b-a450-5033edf370b5</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
