<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Warehouses</name>
   <tag></tag>
   <elementGuidId>da15c89a-d632-448c-9aa7-e0ed677d7540</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'Warehouses')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>a.fw-bold.text-truncate</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:role=link[name=&quot;Warehouses&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>7638c7c0-7183-455c-a41d-fe79e6e6c50b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fw-bold text-truncate</value>
      <webElementGuid>d1a73446-b64d-48ff-b147-70ddba07846c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>/odoo/action-242</value>
      <webElementGuid>2eba7b75-5d40-44f8-a68b-eae547560424</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-tooltip</name>
      <type>Main</type>
      <value>Back to &quot;Warehouses&quot;</value>
      <webElementGuid>8971acb2-bb01-4410-8511-e6b185a34ea5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Warehouses</value>
      <webElementGuid>852b0c72-c898-419a-a1de-1384c96a5805</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;o_web_client&quot;]/div[@class=&quot;o_action_manager&quot;]/div[@class=&quot;o_xxl_form_view h-100 o_form_view o_view_controller o_action&quot;]/div[@class=&quot;o_form_view_container&quot;]/div[@class=&quot;o_control_panel d-flex flex-column gap-3 gap-lg-1 px-3 pt-2 pb-3&quot;]/div[@class=&quot;o_control_panel_main d-flex flex-wrap flex-lg-nowrap justify-content-between align-items-lg-start gap-3 flex-grow-1&quot;]/div[@class=&quot;o_control_panel_breadcrumbs d-flex align-items-center gap-1 order-0 h-lg-100&quot;]/div[@class=&quot;o_breadcrumb d-flex flex-row flex-md-column align-self-stretch justify-content-between min-w-0&quot;]/ol[@class=&quot;breadcrumb flex-nowrap text-nowrap small lh-sm&quot;]/li[@class=&quot;breadcrumb-item d-inline-flex min-w-0 o_back_button&quot;]/a[@class=&quot;fw-bold text-truncate&quot;]</value>
      <webElementGuid>142373f5-e478-44e6-8d0a-5c8ced01cd86</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Warehouses')]</value>
      <webElementGuid>bfc9aa60-ac5a-4b51-9726-fee783242480</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='New'])[2]/following::a[1]</value>
      <webElementGuid>dfd69a7b-678b-4fd6-9ffa-0469a5a15c99</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Toggle Dropdown'])[1]/following::a[1]</value>
      <webElementGuid>7326926d-cdf3-44ed-b289-452623f1c23a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Wqwer'])[2]/preceding::a[1]</value>
      <webElementGuid>599504f9-9c1f-45b3-8fcd-e90c95c53d70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Routes'])[1]/preceding::a[1]</value>
      <webElementGuid>9dc226fa-6489-4d3e-9b6f-4f5bb50add05</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Warehouses']/parent::*</value>
      <webElementGuid>d27b810a-02fe-489c-a92b-6aa4fa9dfb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '/odoo/action-242')]</value>
      <webElementGuid>60e55cae-11cd-44e3-b531-e81758fd0e61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li/a</value>
      <webElementGuid>b3d73648-8610-4ec9-972d-0b69a0c748ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '/odoo/action-242' and (text() = 'Warehouses' or . = 'Warehouses')]</value>
      <webElementGuid>699c3df0-ec3a-4ae1-b562-fc64ae2e27f7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
