<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Receive From_partner_id_0</name>
   <tag></tag>
   <elementGuidId>3d3f219c-c6db-4018-a950-9dd9a779f4be</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#partner_id_0</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='partner_id_0']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:label=&quot;Receive From&quot;i</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>0ba00e5f-eb6f-48ba-a753-2ac02dcb512c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2128b034-5f33-46da-b120-8bb16ea4a2ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>o-autocomplete--input o_input</value>
      <webElementGuid>c6f929fa-24ec-43d2-b66b-271b9e932bba</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>c35bf989-9ea2-4b42-80ef-63b3ca5220ab</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>partner_id_0</value>
      <webElementGuid>cd4c8011-a10c-4059-b48a-1d3f1e58fe2d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;partner_id_0&quot;)</value>
      <webElementGuid>bbc393bc-7848-4df9-98da-8927ac4549aa</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='partner_id_0']</value>
      <webElementGuid>95488453-309c-4c20-aa68-eb41b36656b5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>9f378caa-b389-46d8-9a97-caced6a0ded7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'partner_id_0']</value>
      <webElementGuid>43ab2866-4803-4c93-a659-0a9cb1a4c83d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
